server:
  port: 9877

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loans
    username: postgres
    password: cdac
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never


